
`birthday` date NOT NULL COMMENT '生日',
`age` tinyint(4) NOT NULL COMMENT '年龄',
`sex` tinyint(1) NOT NULL DEFAULT '0' COMMENT '性别:0=男,1=女,2=未知',
`ethnic` varchar(30) DEFAULT NULL COMMENT '民族',
`graduation` varchar(100) DEFAULT NULL COMMENT '毕业学校',
`certificate` char(200) DEFAULT NULL COMMENT '证书编号',
`graduationdate` date DEFAULT NULL COMMENT '毕业时间',
`graduationmajor` varchar(100) DEFAULT NULL COMMENT '毕业专业',
`idcard_positive_image` char(200) DEFAULT NULL COMMENT '身份证正面',
`idcard_negative_image` char(200) DEFAULT NULL COMMENT '身份证反面',
`graduation_image` char(200) DEFAULT NULL COMMENT '毕业证书照',
`status` tinyint(3) NOT NULL DEFAULT '0' COMMENT '状态:0=未报名,1=已报名,-1=未通过',
`applicationtime` int(11) NOT NULL DEFAULT '0' COMMENT '申请时间',
`result` varchar(255) DEFAULT NULL COMMENT '未通过原因',
`updatetime` int(11) NOT NULL DEFAULT '0' COMMENT '报名时间,机构向学校提交信息时间',

